/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.kuznecov.pomocnikplanovania.gui;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sk.kuznecov.pomocnikplanovania.FileManager;
import sk.kuznecov.pomocnikplanovania.ludia.Uzivatel;

/**
 *
 * @author Ja
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        tbLogin = new javax.swing.JToolBar();
        LoginPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfEmailLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHesloLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tbRegister = new javax.swing.JToolBar();
        RegisterPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMeno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfHeslo = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tfHeslo2 = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbLogin.setRollover(true);

        LoginPane.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Email");
        LoginPane.add(jLabel1);

        tfEmailLogin.setText("kikprofik@gmail.com");
        LoginPane.add(tfEmailLogin);

        jLabel2.setText("Heslo");
        LoginPane.add(jLabel2);

        tfHesloLogin.setText("13kiko13");
        LoginPane.add(tfHesloLogin);

        btnLogin.setText("Prihlasit");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        LoginPane.add(btnLogin);

        tbLogin.add(LoginPane);

        tabPane.addTab("Prihlasit sa", tbLogin);

        tbRegister.setRollover(true);

        RegisterPane.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setText("Email");
        RegisterPane.add(jLabel3);
        RegisterPane.add(tfEmail);

        jLabel4.setText("Meno");
        RegisterPane.add(jLabel4);
        RegisterPane.add(tfMeno);

        jLabel5.setText("Heslo");
        RegisterPane.add(jLabel5);

        tfHeslo.setText("jPasswordField1");
        RegisterPane.add(tfHeslo);

        jLabel6.setText("Znovu Heslo");
        RegisterPane.add(jLabel6);

        tfHeslo2.setText("jPasswordField1");
        RegisterPane.add(tfHeslo2);

        btnRegister.setText("Vytvorit ucet");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        RegisterPane.add(btnRegister);

        tbRegister.add(RegisterPane);

        tabPane.addTab("Registrovat sa", tbRegister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        Uzivatel user;
        try {
            user = FileManager.prihlasit(tfEmailLogin.getText(), tfHesloLogin.getText());
            if(user !=null){
            Window window;
            window = new Window(user);
            window.setVisible(true);
            setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Email, alebo heslo je zle!");
            }
        } catch (IOException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked

        if (!tfEmail.getText().contains("-") && !tfMeno.getText().contains("-") && !tfHeslo.getText().contains("-")) {
            if (tfEmail.getText().contains("@") && tfEmail.getText().contains(".")) {
                if ((tfHeslo.getText().length() >= 8) && (tfMeno.getText().length() >= 8)) {
                    if (tfHeslo.getText().equals(tfHeslo2.getText())) {

                            FileManager.registrovat(tfEmail.getText(), tfMeno.getText(), tfHeslo.getText());
                            tabPane.setSelectedComponent(tbLogin);
                            JOptionPane.showMessageDialog(this, "Registracia prebehla uspesne");

                    } else {
                        if (tfHeslo2.getText().length() == 0) {
                            JOptionPane.showMessageDialog(this, "Zopakuj heslo!");
                        } else {
                            JOptionPane.showMessageDialog(this, "Hesla sa nezhoduju!");
                        }

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Meno, Heslo musi mat viac ako 8 znakov!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Zadajte platny email");
            }
        } else {
            JOptionPane.showMessageDialog(this, "'-' je neplatny znak!");
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPane;
    private javax.swing.JPanel RegisterPane;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JToolBar tbLogin;
    private javax.swing.JToolBar tbRegister;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailLogin;
    private javax.swing.JPasswordField tfHeslo;
    private javax.swing.JPasswordField tfHeslo2;
    private javax.swing.JPasswordField tfHesloLogin;
    private javax.swing.JTextField tfMeno;
    // End of variables declaration//GEN-END:variables
}
