/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.kuznecov.pomocnikplanovania.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import sk.kuznecov.pomocnikplanovania.ludia.Uzivatel;
import sk.kuznecov.pomocnikplanovania.gui.NovaUdalost;
import sk.kuznecov.pomocnikplanovania.rozvrh.RozvrhMesiac;
import sk.kuznecov.pomocnikplanovania.rozvrh.RozvrhTyzden;
import sk.kuznecov.pomocnikplanovania.subory.UpdateThread;

/**
 *
 * @author Ja
 */
public class Window extends javax.swing.JFrame {

    private static final String TITLE_DIALOG_NOVA_UDALOST = "Vytvorenie Novej Udalosti";
    private Uzivatel prihlaseny;
    private boolean running;

    /**
     * Creates new form Window
     */
    UpdateThread updateThread;

    public Window(Uzivatel user) {
        initComponents();
        this.prihlaseny = prihlaseny;
        updateThread = new UpdateThread("Update Thread");
        updateThread.start();
        running = true;
        setTitle("Pomocnik Planovania");
        new Thread() {
            public void run() {
                while (running) {
                    try {
                        sleep(5000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                    //Nacitaj zmeny v Planoch
                    //Nacitaj nove Plany
                    //ak boli pridane z ineho "zariadenia" v ten isty cas
                    
                    
                    //test
                    btnThreadTest.setText(UpdateThread.getSSS());
                    btnThreadTest.revalidate();
                    btnThreadTest.repaint();
                }
            }
        }.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPane = new javax.swing.JPanel();
        MenuPane = new javax.swing.JPanel();
        btnRozvrh = new javax.swing.JButton();
        btnNovyPlan = new javax.swing.JButton();
        btnThreadTest = new javax.swing.JButton();
        btnShowMonth = new javax.swing.JButton();
        btnShowWeek = new javax.swing.JButton();
        btnNastavenia = new javax.swing.JButton();
        canvasPane = new sk.kuznecov.pomocnikplanovania.gui.Canvas();
        FooterPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        HeaderPane.setBackground(new java.awt.Color(204, 204, 255));

        MenuPane.setBackground(new java.awt.Color(204, 255, 204));
        MenuPane.setLayout(new java.awt.GridLayout(20, 1));

        btnRozvrh.setText("Zobraz Rozvrh");
        btnRozvrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRozvrhMouseClicked(evt);
            }
        });
        MenuPane.add(btnRozvrh);

        btnNovyPlan.setText("Nový Plán");
        btnNovyPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovyPlanMouseClicked(evt);
            }
        });
        MenuPane.add(btnNovyPlan);

        btnThreadTest.setText("0");
        MenuPane.add(btnThreadTest);

        btnShowMonth.setText("Zobraz Mesiac");
        btnShowMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMonthMouseClicked(evt);
            }
        });
        MenuPane.add(btnShowMonth);

        btnShowWeek.setText("Zobraz Tyzden");
        btnShowWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowWeekMouseClicked(evt);
            }
        });
        MenuPane.add(btnShowWeek);

        btnNastavenia.setText("Nastavenia");
        btnNastavenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNastaveniaMouseClicked(evt);
            }
        });
        MenuPane.add(btnNastavenia);

        FooterPane.setBackground(new java.awt.Color(255, 204, 204));
        FooterPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Odhlasit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        FooterPane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FooterPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(canvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(HeaderPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPane, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(canvasPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FooterPane, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MenuPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void btnNovyPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovyPlanMouseClicked
        JOptionPane pane = new JOptionPane();
        JDialog dialog = pane.createDialog(TITLE_DIALOG_NOVA_UDALOST);
        dialog.setContentPane(new NovaUdalost());
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNovyPlanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNastaveniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNastaveniaMouseClicked
        System.out.println("Nastavenia btn clicked");
        canvasPane.removeAll();
        Nastavenia nastaveniaPnl = new Nastavenia();
        canvasPane.add(nastaveniaPnl);
        canvasPane.revalidate();
        canvasPane.repaint();
        btnRozvrh.setVisible(true);
        btnNastavenia.setVisible(false);

    }//GEN-LAST:event_btnNastaveniaMouseClicked

    private void btnRozvrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRozvrhMouseClicked
        System.out.println("Nastavenia btn clicked");
        canvasPane.removeAll();
        RozvrhMesiac rozvrh = new RozvrhMesiac();
        canvasPane.add(rozvrh);
        canvasPane.revalidate();
        canvasPane.repaint();
        btnNastavenia.setVisible(true);
        btnRozvrh.setVisible(false);
    }//GEN-LAST:event_btnRozvrhMouseClicked

    private void btnShowMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMonthMouseClicked
        canvasPane.rozvrh = new RozvrhMesiac();
        canvasPane.obnovRozvrh();
    }//GEN-LAST:event_btnShowMonthMouseClicked

    private void btnShowWeekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowWeekMouseClicked
        canvasPane.rozvrh = new RozvrhTyzden();
        canvasPane.obnovRozvrh();
    }//GEN-LAST:event_btnShowWeekMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPane;
    private javax.swing.JPanel HeaderPane;
    private javax.swing.JPanel MenuPane;
    private javax.swing.JButton btnNastavenia;
    private javax.swing.JButton btnNovyPlan;
    private javax.swing.JButton btnRozvrh;
    private javax.swing.JButton btnShowMonth;
    private javax.swing.JButton btnShowWeek;
    private javax.swing.JButton btnThreadTest;
    private sk.kuznecov.pomocnikplanovania.gui.Canvas canvasPane;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
