package sk.kuznecov.pomocnikplanovania;


import com.sun.awt.SecurityWarning;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Polygon;
import sk.kuznecov.pomocnikplanovania.rozvrh.RozvrhTyzden;
import sk.kuznecov.pomocnikplanovania.rozvrh.plan.Plan;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ja
 */
public class Canvas extends javax.swing.JPanel {

    /**
     * Creates new form Canvas
     */
    public RozvrhTyzden rozvrh;
    
    public Canvas() {
        
        initComponents();
        rozvrh = new RozvrhTyzden(0, 0, 400, 400);
        
        add(new Plan(20,20,40,50));
        validate();
        repaint();
    }
    
    public final void createRozvrh(int width, int height){
        rozvrh = new RozvrhTyzden(0, 0, width, height);
    }
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        //rozvrh.render(g);
        //validate();
        //repaint();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane6 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSplitPane jSplitPane6;
    // End of variables declaration//GEN-END:variables
}
