/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.kuznecov.pomocnikplanovania;

/**
 *
 * @author Ja
 */
public class SignIO extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public SignIO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        LoginPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        RegisterPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        LoginPane.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Meno");
        LoginPane.add(jLabel1);

        jTextField3.setText("jTextField3");
        LoginPane.add(jTextField3);

        jLabel2.setText("Heslo");
        LoginPane.add(jLabel2);

        jPasswordField4.setText("jPasswordField1");
        LoginPane.add(jPasswordField4);

        jButton1.setText("Registrovat");
        LoginPane.add(jButton1);

        jToolBar1.add(LoginPane);

        jTabbedPane1.addTab("Prihlasit sa", jToolBar1);

        jToolBar2.setRollover(true);

        RegisterPane.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setText("Email");
        RegisterPane.add(jLabel3);

        jTextField1.setText("jTextField1");
        RegisterPane.add(jTextField1);

        jLabel4.setText("Meno");
        RegisterPane.add(jLabel4);

        jTextField2.setText("jTextField1");
        RegisterPane.add(jTextField2);

        jLabel5.setText("Heslo");
        RegisterPane.add(jLabel5);

        jPasswordField1.setText("jPasswordField1");
        RegisterPane.add(jPasswordField1);

        jLabel6.setText("Znovu Heslo");
        RegisterPane.add(jLabel6);

        jPasswordField2.setText("jPasswordField1");
        RegisterPane.add(jPasswordField2);

        jButton2.setText("Prihlasit sa");
        RegisterPane.add(jButton2);

        jToolBar2.add(RegisterPane);

        jTabbedPane1.addTab("Registrovat sa", jToolBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPane;
    private javax.swing.JPanel RegisterPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
