/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.kuznecov.pomocnikplanovania.gui.list_elements;

/**
 *
 * @author Ja
 */
public class ClovekZaznam extends javax.swing.JPanel {

    /**
     * Creates new form ClovekZaznam
     */
    public ClovekZaznam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        jLabel1.setText("Meno Priezvisko");
        add(jLabel1);

        jLabel2.setText("Email");
        add(jLabel2);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Skupina, Skupina, Skupina");
        jPanel1.add(jLabel3, new java.awt.GridBagConstraints());

        jButton1.setText("...");
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
